### ISSUE TITLE
Invalid Discord invite link

### ISSUE THREAD

**Issue by benjaminforras** [ng-primitives/ng-primitives#15]
### Describe the problem that you experienced

When I try to join, it shows that the invite was expired.

**Comment by ajitzero** [comment]
This link works for me!

**Comment by ashley-hunter** [comment]
Excellent! Thank you!

**Comment by ashley-hunter** [comment]
Hmm, strange. The invite link had no expiration and unlimited usage, so should be ok. The only thing I see is that a verified email address is required - it won't let me select no restrictions- could that be why you're not able to access?

![image](https://github.com/user-attachments/assets/856cb308-3223-433d-8496-492a969e83c6)

**Comment by benjaminforras** [comment]
Strange, I was able to join by copying the link and pasting it to the discord application.
Thanks!

**Comment by ashley-hunter** [comment]
Excellent! Strange, but glad you were able to join! Welcome!
