### ISSUE TITLE
generators.json is missing from the installed package

### ISSUE THREAD

**Issue by benjaminforras** [ng-primitives/ng-primitives#28]
### Version

0.5.0

### Bug Description

When I use the `ng add ng-primitives` command it'll install the package but returns an error at the end.
![image](https://github.com/user-attachments/assets/e3d41830-6d31-4d89-8a63-365a5ff9754a)

When checking node_modules, the generators.json file is indeed missing:
![image](https://github.com/user-attachments/assets/bc07b8ae-fe28-4b7d-ac7b-1961761d0ca9)

**Comment by ashley-hunter** [comment]
Thank you for the report, this should now be resolved in v0.5.1

**Comment by benjaminforras** [comment]
Awesome! Thanks for the quick fix!

**Comment by ashley-hunter** [comment]
No problem 😊
