### ISSUE TITLE
bug: `NgpError` does not respond to validation errors from the parent (`FormGroup`)

### ISSUE THREAD

**Issue by gsiwiec01** [ng-primitives/ng-primitives#39]
### Affected Primitive

NgpError

### Version

0.7.1

### Bug Description

Validation failures for validators that were added not directly to the FormControl, but to the FormGroup, are not detected by NgpError.

### Reproduction

https://stackblitz.com/edit/angular-jjkqam?file=src%2Fmain.ts

**Comment by ashley-hunter** [comment]
Thank you for the report! I was looking into this a bit and was curious if you could provide me with a bit of information about your specific use case? Are you attaching the error to a form field in the form, or are you showing an error for the form itself?
Im trying to work out is this something that should "fallback" to form validation if not used within a form field, or is there a case for needing to listen for both errors on the form field and form. Thanks!

**Comment by gsiwiec01** [comment]
> Thank you for the report! I was looking into this a bit and was curious if you could provide me with a bit of information about your specific use case? Are you attaching the error to a form field in the form, or are you showing an error for the form itself? Im trying to work out is this something that should "fallback" to form validation if not used within a form field, or is there a case for needing to listen for both errors on the form field and form. Thanks!

Hi. Essentially, you’re right that there usually isn’t a need for your primitives to listen to the entire form. I didn’t consider this in a broader context. In general, I created an adapter for Zod, and that’s where the error is coming from, as it inserts Record<string, string[]> into the form errors. So, requiring listening to form errors is very specific to my application. Sorry for the trouble!

**Comment by ashley-hunter** [comment]
Its no problem at all! Its good to discuss these kinds of scenarios! I'll close this for now, but if you do find any other cases that haven't been covered reach out 😊 thank you!
