### ISSUE TITLE
Support older Angular Versions

### ISSUE THREAD

**Issue by bigfatbird** [ng-primitives/ng-primitives#67]
### Feature Type

Enhancement

### Feature Description

Might consider supporting older angular versions to help people migrating from older projects < Angular V18

**Comment by ashley-hunter** [comment]
Hi, thank you for the feedback! 

This is something I would have loved to be able to do, but are a bit limited unfortunately. When starting this project we decided to go all in with signals, as a result relying on signal inputs, outputs, models etc.. this future proofs the project and means we wont need to do a large rewrite in future causing breaking changes to support things like zoneless or provide the best possible performance. As some of these features only came along in recent versions of Angular we aren't able to support older versions. 

It *may* be possible to support Angular 17.3 or higher, I can't recall if we are relying on any APIs that were introduced only in 18, so I'll try and look into that and see if there is anyway we could support even the latest minor of v17.
